# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e3461a9206006f02591e8999076ad89b0fe28ac791839bdb51504bcc8dfc2120e76a7354c4a5ec9bf33655a89d2914aa84a0deaef654e1a6603f974145183f

test:
  secret_key_base: b4b56ec354844f74efda921c575f8550ebeebf33c12f1eed19ead14cdbdfa8769f6617300b380e480f340c600b9ba662003011c6e58f9dd1e0c4454429faa1e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
